### ISSUE TITLE
ableC-triggered extension builds occasionally use an old ableC version

### ISSUE THREAD

**Issue by krame505** [melt-umn/jenkins-lib#4]
For example, I have no idea why this build failed: http://coldpress.cs.umn.edu:8080/job/melt-umn/job/ableC/job/develop/69/
Subsequently I triggered another ableC build manually and everything built fine.

**Comment by tedinski** [comment]
This appears to be multiple bugs:

1. Sometimes, some things are generating files in `custom-workspace/silver/generated` which means some builds aren't setting `-G`. I'm thinking about doing some `chmod` work to try to make this error early whenever it happens, let me see... Hmm. Or maybe I could set the environment variable instead of using `-G`... Or both.
2. Something in `ableC_sample_projects` specifically is ignoring `ABLEC_BASE`. I'll check that out, too...

**Comment by tedinski** [comment]
Hopefully this is now fixed. Reopen if it reoccurs.
